/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    inquiries: Inquiry;
    'medical-intakes': MedicalIntake;
    services: Service;
    pricing: Pricing;
    providers: Provider;
    pages: Page;
    media: Media;
    conditions: Condition;
    insurances: Insurance;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'medical-intakes': MedicalIntakesSelect<false> | MedicalIntakesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    conditions: ConditionsSelect<false> | ConditionsSelect<true>;
    insurances: InsurancesSelect<false> | InsurancesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Each tenant represents a separate brand / site (e.g. UrgentCare Indy, PrimaryCare Indy).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Brand name shown in the UI (e.g. "UrgentCare Indy").
   */
  name: string;
  /**
   * Machine-readable key (e.g. "urgent-care", "primary-care"). Used in routing & headers.
   */
  slug: string;
  /**
   * Hostnames that map to this tenant (e.g. "urgentcareindy.com", "localhost").
   */
  domains: {
    domain: string;
    id?: string | null;
  }[];
  /**
   * Controls CSS theme tokens on the front-end.
   */
  theme: 'teal-orange' | 'navy-gold';
  /**
   * Brand logo displayed in the Navbar.
   */
  logo?: (number | null) | Media;
  /**
   * Estimated wait in minutes. Shown in the Hero block.
   */
  currentWaitTime: number;
  /**
   * Uncheck when the clinic is closed or on holidays.
   */
  isOpen?: boolean | null;
  /**
   * Insurance plans currently accepted by this tenant.
   */
  acceptedInsurances?: (number | Insurance)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded images and files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text for accessibility (WCAG 2.1).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Insurance plans accepted at UrgentCare Indy locations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insurances".
 */
export interface Insurance {
  id: number;
  /**
   * e.g. "Anthem Blue Cross Blue Shield"
   */
  name: string;
  planType?: ('PPO' | 'HMO' | 'EPO' | 'Medicaid' | 'Medicare' | 'Other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Leads & patient inquiries from web forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  /**
   * The brand / site this inquiry originated from.
   */
  tenant: number | Tenant;
  firstName: string;
  lastName: string;
  email: string;
  /**
   * If checked the contact will be synced to Mailchimp via the afterChange hook.
   */
  marketingConsent?: boolean | null;
  status: 'Lead' | 'IntakeStarted' | 'SyncedToEMR';
  updatedAt: string;
  createdAt: string;
}
/**
 * Full patient intake records linked to an Inquiry.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-intakes".
 */
export interface MedicalIntake {
  id: number;
  /**
   * The Inquiry (lead) this intake belongs to.
   */
  inquiry: number | Inquiry;
  dateOfBirth: string;
  gender: 'M' | 'F' | 'U';
  address: {
    street: string;
    city: string;
    /**
     * Two-letter US state abbreviation
     */
    state: string;
    /**
     * 5-digit US ZIP code
     */
    zip: string;
  };
  /**
   * Primary reason for visit.
   */
  chiefComplaint: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Medical services offered across all locations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * The brand / site this service belongs to.
   */
  tenant: number | Tenant;
  title: string;
  /**
   * URL-safe identifier (e.g. "x-rays"). Auto-generated later via hook.
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Lucide React icon rendered on the front-end.
   */
  icon:
    | 'Stethoscope'
    | 'HeartPulse'
    | 'Thermometer'
    | 'Syringe'
    | 'Pill'
    | 'Baby'
    | 'Bone'
    | 'ScanLine'
    | 'Activity'
    | 'Microscope'
    | 'Ear'
    | 'Eye'
    | 'Brain'
    | 'Hand'
    | 'ShieldCheck'
    | 'Clock'
    | 'ClipboardList'
    | 'Zap';
  /**
   * Service category for filtering and organization.
   */
  category:
    | 'Urgent'
    | 'Primary'
    | 'Pulmonary'
    | 'Cardiology'
    | 'Orthopedics'
    | 'Dermatology'
    | 'MentalHealth'
    | 'PhysicalTherapy';
  /**
   * Associated pricing tier for this service.
   */
  priceLevel?: (number | null) | Pricing;
  updatedAt: string;
  createdAt: string;
}
/**
 * Service pricing tiers and packages offered by each tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  /**
   * The brand / site this pricing tier belongs to.
   */
  tenant: number | Tenant;
  /**
   * Tier name (e.g., "Basic", "Standard", "Premium").
   */
  levelName: string;
  /**
   * Price in USD (e.g., 99.99).
   */
  price: number;
  /**
   * Brief description of what this tier includes.
   */
  description: string;
  /**
   * Which clinic type this pricing applies to.
   */
  siteType: 'Urgent' | 'Primary';
  /**
   * List of services/features included in this pricing tier.
   */
  includes?:
    | {
        /**
         * e.g., "Basic consultation", "Lab work".
         */
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clinical staff and providers. Includes profiles for "Meet the Team" content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  /**
   * The brand / site this provider belongs to.
   */
  tenant: number | Tenant;
  /**
   * Full name (e.g., "Dr. Jane Smith").
   */
  name: string;
  /**
   * Credentials/title (e.g., "MD", "NP", "PA-C", "RN").
   */
  title: string;
  /**
   * Area of expertise (e.g., "Family Medicine", "Urgent Care", "Pediatrics").
   */
  specialty: string;
  /**
   * Biographical summary for the "Meet the Team" section.
   */
  bio?: string | null;
  /**
   * URL to a short video (YouTube, Vimeo, etc.) for "Meet the Team" shorts.
   */
  videoUrl?: string | null;
  /**
   * Professional headshot for the team page.
   */
  headshot?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dynamic pages built with content blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The brand / site this page belongs to.
   */
  tenant: number | Tenant;
  title: string;
  /**
   * URL path segment (e.g. "about-us"). Must be unique.
   */
  slug: string;
  /**
   * SEO meta description.
   */
  metaDescription?: string | null;
  blocks: (
    | {
        title: string;
        subtitle?: string | null;
        /**
         * Button text for the primary call-to-action.
         */
        ctaLabel?: string | null;
        /**
         * Display the live "current wait time" badge in the hero.
         */
        showWaitTime?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading?: string | null;
        /**
         * Select the services to display in this grid.
         */
        services: (number | Service)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceGrid';
      }
    | {
        image: number | Media;
        /**
         * Which side the image appears on.
         */
        imagePosition?: ('left' | 'right') | null;
        richText: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaContent';
      }
    | {
        heading?: string | null;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Medical conditions treated at UrgentCare Indy. Each one creates an SEO-friendly page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conditions".
 */
export interface Condition {
  id: number;
  /**
   * The brand / site this condition belongs to.
   */
  tenant: number | Tenant;
  /**
   * e.g. "Strep Throat", "Sprained Ankle"
   */
  title: string;
  slug: string;
  /**
   * Symptoms patients search for (powers the QuickSearch component).
   */
  commonSymptoms: {
    symptom: string;
    id?: string | null;
  }[];
  /**
   * Services used to diagnose/treat this condition.
   */
  relatedServices?: (number | Service)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'medical-intakes';
        value: number | MedicalIntake;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'conditions';
        value: number | Condition;
      } | null)
    | ({
        relationTo: 'insurances';
        value: number | Insurance;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  theme?: T;
  logo?: T;
  currentWaitTime?: T;
  isOpen?: T;
  acceptedInsurances?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  tenant?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  marketingConsent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-intakes_select".
 */
export interface MedicalIntakesSelect<T extends boolean = true> {
  inquiry?: T;
  dateOfBirth?: T;
  gender?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  chiefComplaint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  category?: T;
  priceLevel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  tenant?: T;
  levelName?: T;
  price?: T;
  description?: T;
  siteType?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  title?: T;
  specialty?: T;
  bio?: T;
  videoUrl?: T;
  headshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  metaDescription?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              ctaLabel?: T;
              showWaitTime?: T;
              id?: T;
              blockName?: T;
            };
        serviceGrid?:
          | T
          | {
              heading?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        mediaContent?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              richText?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conditions_select".
 */
export interface ConditionsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  commonSymptoms?:
    | T
    | {
        symptom?: T;
        id?: T;
      };
  relatedServices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insurances_select".
 */
export interface InsurancesSelect<T extends boolean = true> {
  name?: T;
  planType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}